# Generated by Django 6.0.6 on 2026-06-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('is_completed', models.BooleanField(default=False)),
                ('wip_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_columns', to='projects.project')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('project', 'position')},
            },
        ),
    ]
