# Generated by Django 6.0.6 on 2026-06-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('estimated_seconds', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workflows.workflowcolumn')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('from_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='workflows.workflowcolumn')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='tasks.task')),
                ('to_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='workflows.workflowcolumn')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
    ]
