import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'
import type { DetailedReport } from '../api/reports'

function fmt(seconds: number): string {
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = seconds % 60
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

const C = {
  primary: '#0051d5',
  lightBg: '#f2f4f7',
  dark: '#191c1e',
  gray: '#45464d',
  border: '#c6c6cd',
  white: '#ffffff',
}

const s = StyleSheet.create({
  page: { padding: 30, paddingTop: 20, fontFamily: 'Helvetica', fontSize: 10, color: C.dark },
  headerBar: { backgroundColor: C.primary, marginHorizontal: -30, marginTop: -20, marginBottom: 16, paddingHorizontal: 30, paddingVertical: 14 },
  headerTitle: { fontSize: 22, fontWeight: 'bold', color: C.white },
  headerSub: { fontSize: 9, color: C.white, marginTop: 2 },
  headerGen: { fontSize: 7, color: C.white, marginTop: 1 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 8, marginTop: 12 },
  summaryRow: { flexDirection: 'row', gap: 8, marginBottom: 4 },
  summaryBox: { flex: 1, backgroundColor: C.lightBg, paddingVertical: 10, paddingHorizontal: 8, alignItems: 'center' },
  summaryLabel: { fontSize: 7, color: C.gray, marginBottom: 2, textTransform: 'uppercase' as const },
  summaryValue: { fontSize: 14, fontWeight: 'bold' },
  projectBox: { marginTop: 10, marginBottom: 8 },
  projectHeader: { backgroundColor: C.lightBg, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6, paddingHorizontal: 8 },
  projectName: { fontSize: 11, fontWeight: 'bold' },
  projectTime: { fontSize: 9, color: C.gray },
  subTableTitle: { fontSize: 9, fontWeight: 'bold', color: C.gray, marginTop: 6, marginBottom: 2, marginLeft: 4 },
  tableRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 3, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: C.border },
  tableRowAlt: { backgroundColor: C.lightBg },
  tableHeader: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.primary, paddingVertical: 4, paddingHorizontal: 8 },
  thText: { fontSize: 7, fontWeight: 'bold', color: C.white },
  tdText: { fontSize: 8 },
  stageDot: { width: 6, height: 6, borderRadius: 3, marginRight: 6 },
  flexRow: { flexDirection: 'row', alignItems: 'center' },
  textRight: { textAlign: 'right' as const },
  footer: { position: 'absolute', bottom: 20, left: 30, right: 30, fontSize: 7, color: C.gray, textAlign: 'center' as const, borderTopWidth: 1, borderTopColor: C.border, paddingTop: 6 },
})

function StageDot({ color }: { color: string }) {
  return <View style={[s.stageDot, { backgroundColor: color }]} />
}

export default function PdfReport({ data }: { data: DetailedReport }) {
  const totalPct = (val: number) =>
    data.summary.total_seconds > 0 ? `${Math.round((val / data.summary.total_seconds) * 100)}%` : '0%'

  return (
    <Document>
      <Page size="A4" style={s.page} wrap>
        <View fixed>
          <Text style={s.footer}>
            Report generated by ChronoFlow on {new Date(data.generated_at).toLocaleString()}
          </Text>
        </View>

        <View style={s.headerBar}>
          <Text style={s.headerTitle}>ChronoFlow Report</Text>
          <Text style={s.headerSub}>
            Period: {data.period.start_date} &mdash; {data.period.end_date}
          </Text>
          <Text style={s.headerGen}>
            Generated: {new Date(data.generated_at).toLocaleString()}
          </Text>
        </View>

        <Text style={s.sectionTitle}>Executive Summary</Text>
        <View style={s.summaryRow}>
          {[
            { label: 'Total Hours', value: fmt(data.summary.total_seconds) },
            { label: 'Sessions', value: String(data.summary.total_sessions) },
            { label: 'Projects', value: String(data.summary.total_projects) },
            { label: 'Tasks', value: String(data.summary.total_tasks) },
          ].map((box) => (
            <View key={box.label} style={s.summaryBox}>
              <Text style={s.summaryLabel}>{box.label}</Text>
              <Text style={s.summaryValue}>{box.value}</Text>
            </View>
          ))}
        </View>

        <Text style={s.sectionTitle}>Project Breakdown</Text>

        {data.projects.map((project) => (
          <View key={project.id} style={s.projectBox} wrap={false}>
            <View style={s.projectHeader}>
              <Text style={s.projectName}>{project.name}</Text>
              <Text style={s.projectTime}>{fmt(project.total_seconds)}</Text>
            </View>

            {project.stages.length > 0 && (
              <View wrap={false}>
                <Text style={s.subTableTitle}>Stages</Text>
                <View style={s.tableHeader}>
                  <View style={{ width: '50%', flexDirection: 'row', alignItems: 'center' }}><Text style={s.thText}>Stage</Text></View>
                  <View style={{ width: '30%' }}><Text style={[s.thText, { textAlign: 'right' }]}>Time</Text></View>
                  <View style={{ width: '20%' }}><Text style={[s.thText, { textAlign: 'right' }]}>%</Text></View>
                </View>
                {project.stages.map((st, i) => (
                  <View key={st.name} style={i % 2 === 1 ? [s.tableRow, s.tableRowAlt] : s.tableRow}>
                    <View style={{ width: '50%', flexDirection: 'row', alignItems: 'center' }}>
                      <StageDot color={st.color} />
                      <Text style={s.tdText}>{st.name}</Text>
                    </View>
                    <View style={{ width: '30%' }}><Text style={[s.tdText, { textAlign: 'right' }]}>{fmt(st.duration_seconds)}</Text></View>
                    <View style={{ width: '20%' }}><Text style={[s.tdText, { textAlign: 'right' }]}>{totalPct(st.duration_seconds)}</Text></View>
                  </View>
                ))}
              </View>
            )}

            {project.tasks.length > 0 && (
              <View wrap={false}>
                <Text style={s.subTableTitle}>Tasks</Text>
                <View style={s.tableHeader}>
                  <View style={{ width: '45%' }}><Text style={s.thText}>Task</Text></View>
                  <View style={{ width: '20%' }}><Text style={s.thText}>Stage</Text></View>
                  <View style={{ width: '20%' }}><Text style={[s.thText, { textAlign: 'right' }]}>Time</Text></View>
                  <View style={{ width: '15%' }}><Text style={[s.thText, { textAlign: 'right' }]}>Sessions</Text></View>
                </View>
                {project.tasks.map((t, i) => (
                  <View key={t.task_id} style={i % 2 === 1 ? [s.tableRow, s.tableRowAlt] : s.tableRow}>
                    <View style={{ width: '45%' }}><Text style={s.tdText}>{t.task_code ? `[${t.task_code}] ${t.title}` : t.title}</Text></View>
                    <View style={{ width: '20%' }}><Text style={s.tdText}>{t.stage}</Text></View>
                    <View style={{ width: '20%' }}><Text style={[s.tdText, { textAlign: 'right' }]}>{fmt(t.duration_seconds)}</Text></View>
                    <View style={{ width: '15%' }}><Text style={[s.tdText, { textAlign: 'right' }]}>{t.session_count}</Text></View>
                  </View>
                ))}
              </View>
            )}
          </View>
        ))}

        {data.daily_totals.length > 0 && (
          <View wrap={false}>
            <Text style={s.sectionTitle}>Daily Totals</Text>
            <View style={s.tableHeader}>
              <View style={{ width: '50%' }}><Text style={s.thText}>Date</Text></View>
              <View style={{ width: '30%' }}><Text style={[s.thText, { textAlign: 'right' }]}>Time</Text></View>
              <View style={{ width: '20%' }}><Text style={[s.thText, { textAlign: 'right' }]}>Sessions</Text></View>
            </View>
            {data.daily_totals.map((d, i) => (
              <View key={d.date} style={i % 2 === 1 ? [s.tableRow, s.tableRowAlt] : s.tableRow}>
                <View style={{ width: '50%' }}>
                  <Text style={s.tdText}>
                    {new Date(d.date).toLocaleDateString('en', {
                      weekday: 'short', month: 'short', day: 'numeric', year: 'numeric',
                    })}
                  </Text>
                </View>
                <View style={{ width: '30%' }}><Text style={[s.tdText, { textAlign: 'right' }]}>{fmt(d.duration_seconds)}</Text></View>
                <View style={{ width: '20%' }}><Text style={[s.tdText, { textAlign: 'right' }]}>{d.session_count}</Text></View>
              </View>
            ))}
          </View>
        )}
      </Page>
    </Document>
  )
}
